package com.bidding.platform.common.dto;

public enum ErrorCode {

    EMAIL_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INVALID_OTP,
    OTP_EXPIRED,
    OTP_ATTEMPT_LIMIT_EXCEEDED,
    USER_BLOCKED,
    INVALID_CREDENTIALS,
    JWT_EXPIRED,
    JWT_INVALID,
    ACCESS_DENIED,
    BAD_REQUEST,
    DATABASE_ERROR,
    SERVER_ERROR,
    CATEGORY_NOT_FOUND,
    PRODUCT_ALREADY_EXISTS,
    PRODUCT_NOT_FOUND,
    DUPLICATE_PARAMETER,
    USER_NOT_REGISTERED,
    FILE_DELETE_FAILED,
    RATE_LIMIT_EXCEEDED,
    ROLE_MISMATCH,
    USER_INACTIVE,
    OTP_ATTEMPTS_EXCEEDED
}
